# Generated by Django 2.2.1 on 2019-06-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
            ],
        ),
    ]
